### ISSUE TITLE
Does not support project depending on another project

### ISSUE THREAD

**Issue by guillaume-tgl** [twilio/apkscale#10]
**Describe the bug**
In my case, this does not work as I have 3 libraries (A, B and C) in my project and libraries B and C depends on library A. Running measureSize for library A works but it throws an error for B and C:

Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find prj-android:gssdk-core:unspecified.
Searched in the following locations:
  - file:/Users/guillaume/.m2/repository/prj-android/gssdk-core/unspecified/gssdk-core-unspecified.pom
  - https://dl.google.com/dl/android/maven2/prj-android/gssdk-core/unspecified/gssdk-core-unspecified.pom
  - https://jcenter.bintray.com/prj-android/gssdk-core/unspecified/gssdk-core-unspecified.pom
  - https://repo.maven.apache.org/maven2/prj-android/gssdk-core/unspecified/gssdk-core-unspecified.pom

From what I understand apkScale tries to add a dependency to library A as an external dependency, rather than a local dependency. And it shouldn't be needed to add local library dependencies since their code should already present since you depend on the current library AAR.

An alternative to excluding local dependencies would to depend on the library project rather than on its AAR (as you suggested here), this way you would get all the dependencies for free.

**Version**
- Version: 0.1.3

**Comment by aaalaniz** [comment]
Thank you @guillaume-tgl 

I'll take another shot at supporting this use case! Enabling the use of `project(..)` in the apkscale project proved to be a little more difficult than I anticipated.

**Comment by guillaume-tgl** [comment]
v0.1.4 is supposed to fix this issue, right?

I've just tried it and I still have my local dependency that is added to the apkscale project with version `unspecified`.
