### ISSUE TITLE
Report is deleted when another Gradle task is run

### ISSUE THREAD

**Issue by guillaume-tgl** [twilio/apkscale#4]
**Describe the bug**
After running the `measureSize` task, the report is correctly reported at `build/apkscale/build/outputs/reports/apkscale.json` but as soon as I run another Gradle task, the report is deleted.

**To Reproduce**
1. Run `./gradlew measureSize`
2. Run another Gradle task such as `./gradlew test`
3. Report is no longer present in `build/apkscale` folder

**Expected behavior**
I would expect the report to be kept.

**Actual behavior**
The report is not present anymore.

**Version**
- Version: 0.1.1

**Comment by aaalaniz** [comment]
Hey @guillaume-tgl 

Does this happen with all gradle tasks or just `test`?

Thanks!

**Comment by aaalaniz** [comment]
Hey @guillaume-tgl 

I am going to close this issue as the size measurement task is only intended to be used after `assemble` tasks. Please reopen if you encounter an issue where the report is unexpectedly deleted.

Thanks!
