### ISSUE TITLE
Does not work when the library uses third-party resources

### ISSUE THREAD

**Issue by guillaume-tgl** [twilio/apkscale#5]
**Describe the bug**
The library for which I want to measure the size depends on Android Support AppCompat and uses the theme `Theme.AppCompat.Light.Dialog.Alert`. When I run the `measureSize` task, I get the following error:
```
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.1.1-bin.zip'.`
```

When I try to assemble the apkscale project manually to get more details about the error, I get the following error:
```
AAPT: error: resource style/Theme.AppCompat.Light.Dialog.Alert (aka com.twilio.apkscale.withlibrary:style/Theme.AppCompat.Light.Dialog.Alert) not found.`
```

And that seems normal since the apkscale project only depends on the AAR of the library but not on its dependencies.

**Expected behavior**
I would expect apkscale to be able to measure the size of the library even if it depends on other dependencies. But I'm unsure if it should also measure the size impact of the library dependencies.

**Actual behavior**
The `measureSize` task fails.

**Version**
- Version: 0.1.1

**Comment by aaalaniz** [comment]
Hey @guillaume-tgl 

Great find!

I think this could be fixed by either including the library's dependency aars directly or including the library as a `project` dependency to the fake app used to measure the size.
